using Paradise.ECS.IntegrationTest;

// The 'World' type alias is generated by the source generator.
// Without [DefaultConfig], it uses Paradise.ECS.DefaultConfig as fallback.
// It resolves to: World<Bit64, ComponentRegistry, DefaultConfig>

Console.WriteLine("=== Paradise.ECS Integration Test ===");
Console.WriteLine();

// Create shared resources
using var sharedMetadata = new SharedArchetypeMetadata();
using var chunkManager = new ChunkManager();

// Create the world using the generated World alias
var world = new World(sharedMetadata, chunkManager);

Console.WriteLine("1. Testing Entity Creation");
Console.WriteLine("----------------------------");

// Spawn empty entity
var emptyEntity = world.Spawn();
Console.WriteLine($"  Created empty entity: {emptyEntity}");
Console.WriteLine($"  Entity count: {world.EntityCount}");

// Create player entity with components using builder
var playerEntity = EntityBuilder.Create()
    .Add(new Position(100, 200))
    .Add(new Velocity(5, 0))
    .Add(new Health(100))
    .Add(default(PlayerTag))
    .Add(new Name("Hero"))
    .Build(world);
Console.WriteLine($"  Created player entity: {playerEntity}");
Console.WriteLine($"  Entity count: {world.EntityCount}");

// Create multiple enemy entities
var enemies = new Entity[5];
for (int i = 0; i < enemies.Length; i++)
{
    enemies[i] = EntityBuilder.Create()
        .Add(new Position(i * 50, 300))
        .Add(new Velocity(-2, 0))
        .Add(new Health(50))
        .Add(default(EnemyTag))
        .Build(world);
}
Console.WriteLine($"  Created {enemies.Length} enemy entities");
Console.WriteLine($"  Entity count: {world.EntityCount}");
Console.WriteLine();

Console.WriteLine("2. Testing Component Access");
Console.WriteLine("----------------------------");

// Read components
var playerPos = world.GetComponent<Position>(playerEntity);
var playerHealth = world.GetComponent<Health>(playerEntity);
var playerName = world.GetComponent<Name>(playerEntity);
Console.WriteLine($"  Player position: {playerPos}");
Console.WriteLine($"  Player health: {playerHealth}");
Console.WriteLine($"  Player name: {playerName}");

// Modify component
world.SetComponent(playerEntity, new Position(150, 250));
playerPos = world.GetComponent<Position>(playerEntity);
Console.WriteLine($"  Updated player position: {playerPos}");

// Check for components
Console.WriteLine($"  Player has Position: {world.HasComponent<Position>(playerEntity)}");
Console.WriteLine($"  Player has PlayerTag: {world.HasComponent<PlayerTag>(playerEntity)}");
Console.WriteLine($"  Player has EnemyTag: {world.HasComponent<EnemyTag>(playerEntity)}");
Console.WriteLine();

Console.WriteLine("3. Testing Structural Changes");
Console.WriteLine("----------------------------");

// Add component to empty entity
world.AddComponent(emptyEntity, new Position(0, 0));
Console.WriteLine($"  Added Position to empty entity");
Console.WriteLine($"  Empty entity has Position: {world.HasComponent<Position>(emptyEntity)}");

// Remove component
world.RemoveComponent<Position>(emptyEntity);
Console.WriteLine($"  Removed Position from entity");
Console.WriteLine($"  Entity has Position: {world.HasComponent<Position>(emptyEntity)}");
Console.WriteLine();

Console.WriteLine("4. Testing Entity Lifecycle");
Console.WriteLine("----------------------------");

Console.WriteLine($"  Entity count before despawn: {world.EntityCount}");
Console.WriteLine($"  Enemy[0] is alive: {world.IsAlive(enemies[0])}");

// Despawn an enemy
world.Despawn(enemies[0]);
Console.WriteLine($"  Despawned enemy[0]");
Console.WriteLine($"  Enemy[0] is alive: {world.IsAlive(enemies[0])}");
Console.WriteLine($"  Entity count after despawn: {world.EntityCount}");

// Try to despawn again (should return false)
var despawnedAgain = world.Despawn(enemies[0]);
Console.WriteLine($"  Despawn enemy[0] again: {despawnedAgain}");
Console.WriteLine();

Console.WriteLine("5. Simulating Game Loop (5 frames)");
Console.WriteLine("----------------------------");

// Simple movement system simulation
for (int frame = 0; frame < 5; frame++)
{
    Console.WriteLine($"  Frame {frame + 1}:");

    // Update player position based on velocity
    if (world.IsAlive(playerEntity))
    {
        var pos = world.GetComponent<Position>(playerEntity);
        var vel = world.GetComponent<Velocity>(playerEntity);
        var newPos = new Position(pos.X + vel.X, pos.Y + vel.Y);
        world.SetComponent(playerEntity, newPos);
        Console.WriteLine($"    Player moved to {newPos}");
    }

    // Update enemy positions
    int aliveEnemies = 0;
    foreach (var enemy in enemies)
    {
        if (!world.IsAlive(enemy)) continue;
        aliveEnemies++;

        var pos = world.GetComponent<Position>(enemy);
        var vel = world.GetComponent<Velocity>(enemy);
        var newPos = new Position(pos.X + vel.X, pos.Y + vel.Y);
        world.SetComponent(enemy, newPos);
    }
    Console.WriteLine($"    Updated {aliveEnemies} enemies");
}
Console.WriteLine();

Console.WriteLine("6. Testing Entity Overwrite");
Console.WriteLine("----------------------------");

// Overwrite player with completely new components
Console.WriteLine($"  Player before overwrite - Position: {world.GetComponent<Position>(playerEntity)}");
Console.WriteLine($"  Player has Velocity: {world.HasComponent<Velocity>(playerEntity)}");

EntityBuilder.Create()
    .Add(new Position(0, 0))
    .Add(new Health(200))
    .Add(default(PlayerTag))
    .Overwrite(playerEntity, world);

Console.WriteLine($"  Player after overwrite - Position: {world.GetComponent<Position>(playerEntity)}");
Console.WriteLine($"  Player has Velocity: {world.HasComponent<Velocity>(playerEntity)}");
Console.WriteLine($"  Player health: {world.GetComponent<Health>(playerEntity)}");
Console.WriteLine();

Console.WriteLine("7. Testing World Clear");
Console.WriteLine("----------------------------");

Console.WriteLine($"  Entity count before clear: {world.EntityCount}");
world.Clear();
Console.WriteLine($"  World cleared");
Console.WriteLine($"  Entity count after clear: {world.EntityCount}");
Console.WriteLine($"  Player is alive after clear: {world.IsAlive(playerEntity)}");
Console.WriteLine();

Console.WriteLine("8. Verifying Generated Types");
Console.WriteLine("----------------------------");

// Verify the ComponentMask alias works
Console.WriteLine($"  ComponentMask type: {typeof(ComponentMask).FullName}");

// Verify the World alias works
Console.WriteLine($"  World type: {typeof(World).FullName}");

// Verify component type IDs are assigned
Console.WriteLine($"  Position.TypeId: {Position.TypeId}");
Console.WriteLine($"  Velocity.TypeId: {Velocity.TypeId}");
Console.WriteLine($"  Health.TypeId: {Health.TypeId}");
Console.WriteLine($"  PlayerTag.TypeId: {PlayerTag.TypeId}");
Console.WriteLine($"  EnemyTag.TypeId: {EnemyTag.TypeId}");
Console.WriteLine($"  Name.TypeId: {Name.TypeId}");

// Verify component GUIDs
Console.WriteLine($"  Position.Guid: {Position.Guid}");
Console.WriteLine($"  PlayerTag.Guid: {PlayerTag.Guid}");

// Verify component sizes
Console.WriteLine($"  Position.Size: {Position.Size} bytes");
Console.WriteLine($"  Health.Size: {Health.Size} bytes");
Console.WriteLine($"  PlayerTag.Size: {PlayerTag.Size} bytes (tag component)");
Console.WriteLine($"  Name.Size: {Name.Size} bytes");

// Verify ComponentRegistry
Console.WriteLine($"  ComponentRegistry.TypeInfos.Length: {ComponentRegistry.TypeInfos.Length}");
Console.WriteLine();

Console.WriteLine("=== Integration Test Complete ===");
Console.WriteLine("All operations executed successfully!");

return 0;
