using System.Collections.Immutable;

namespace Paradise.ECS;

/// <summary>
/// Compile-time metadata for a system, describing its component access patterns,
/// dependency edges, and query description. Generated by the source generator.
/// </summary>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
public readonly struct SystemMetadata<TMask>
    where TMask : unmanaged, IBitSet<TMask>
{
    /// <summary>
    /// The unique system ID assigned at compile time.
    /// </summary>
    public int SystemId { get; init; }

    /// <summary>
    /// The fully qualified type name of the system.
    /// </summary>
    public string TypeName { get; init; }

    /// <summary>
    /// Bitmask of components this system reads (includes both read-only and read-write).
    /// </summary>
    public TMask ReadMask { get; init; }

    /// <summary>
    /// Bitmask of components this system writes (read-write access only).
    /// </summary>
    public TMask WriteMask { get; init; }

    /// <summary>
    /// The query description used to find matching archetypes.
    /// Pre-wrapped in HashedKey for efficient lookup.
    /// </summary>
    public HashedKey<ImmutableQueryDescription<TMask>> QueryDescription { get; init; }

    /// <summary>
    /// System IDs that this system must execute after (explicit dependency edges).
    /// Normalized from both <c>[After&lt;T&gt;]</c> and <c>[Before&lt;T&gt;]</c> attributes.
    /// </summary>
    public ImmutableArray<int> AfterSystemIds { get; init; }
}
