namespace Paradise.ECS;

/// <summary>
/// Interface for queryable data types that provide per-entity component access.
/// Implementations are generated by the source generator for each [Queryable] type.
/// </summary>
/// <typeparam name="TSelf">The implementing type (CRTP pattern).</typeparam>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
/// <typeparam name="TConfig">The world configuration type.</typeparam>
public interface IQueryData<TSelf, TMask, TConfig>
    where TSelf : IQueryData<TSelf, TMask, TConfig>, allows ref struct
    where TMask : unmanaged, IBitSet<TMask>
    where TConfig : IConfig, new()
{
    /// <summary>
    /// Creates a new instance of the data type for the specified entity location.
    /// </summary>
    /// <param name="chunkManager">The chunk manager for memory access.</param>
    /// <param name="layout">The archetype layout describing component offsets.</param>
    /// <param name="chunk">The chunk handle containing the entity.</param>
    /// <param name="indexInChunk">The entity's index within the chunk.</param>
    /// <returns>A new data instance providing component access.</returns>
    static abstract TSelf Create(
        ChunkManager chunkManager,
        ImmutableArchetypeLayout<TMask, TConfig> layout,
        ChunkHandle chunk,
        int indexInChunk);
}

/// <summary>
/// Interface for queryable chunk data types that provide batch component access via spans.
/// Implementations are generated by the source generator for each [Queryable] type.
/// </summary>
/// <typeparam name="TSelf">The implementing type (CRTP pattern).</typeparam>
/// <typeparam name="TMask">The component mask type implementing IBitSet.</typeparam>
/// <typeparam name="TConfig">The world configuration type.</typeparam>
public interface IQueryChunkData<TSelf, TMask, TConfig>
    where TSelf : IQueryChunkData<TSelf, TMask, TConfig>, allows ref struct
    where TMask : unmanaged, IBitSet<TMask>
    where TConfig : IConfig, new()
{
    /// <summary>
    /// Creates a new instance of the chunk data type for the specified chunk.
    /// </summary>
    /// <param name="chunkManager">The chunk manager for memory access.</param>
    /// <param name="layout">The archetype layout describing component offsets.</param>
    /// <param name="chunk">The chunk handle.</param>
    /// <param name="entityCount">The number of entities in this chunk.</param>
    /// <returns>A new chunk data instance providing span-based component access.</returns>
    static abstract TSelf Create(
        ChunkManager chunkManager,
        ImmutableArchetypeLayout<TMask, TConfig> layout,
        ChunkHandle chunk,
        int entityCount);
}
