using Paradise.ECS.Sample.Samples;

// The 'World' type alias is generated by the source generator when Paradise.ECS.Tag is referenced.
// It resolves to: TaggedWorld<Bit64, ComponentRegistry, DefaultConfig, EntityTags, TagMask>

Console.WriteLine("=== Paradise.ECS Sample Application ===");
Console.WriteLine();

// Create the world using the generated World alias
// TaggedWorld now creates its own ChunkManager and SharedArchetypeMetadata internally
using var world = new World();

// Run all samples in sequence
var (emptyEntity, playerEntity, enemies) = EntityCreationSample.Run(world);
ComponentAccessSample.Run(world, playerEntity);
TagSystemSample.Run(world, playerEntity);
StructuralChangesSample.Run(world, emptyEntity);
EntityLifecycleSample.Run(world, enemies);
var movableQuery = ComponentQuerySample.Run(world);
TagQuerySample.Run(world, playerEntity);
GameLoopSample.Run(world, movableQuery);
EntityOverwriteSample.Run(world, playerEntity);
GeneratedTypesSample.Run();
WorldClearSample.Run(world, playerEntity);

Console.WriteLine("=== Sample Application Complete ===");
Console.WriteLine("All operations executed successfully!");

return 0;
