using Paradise.ECS.Sample;
using Paradise.ECS.Sample.Samples;

// The 'World' type alias is generated by the source generator when Paradise.ECS.Tag is referenced.
// It resolves to: TaggedWorld<Bit64, ComponentRegistry, GameConfig, EntityTags, TagMask>

Console.WriteLine("=== Paradise.ECS Sample Application ===");
Console.WriteLine();

// Create the dependencies for TaggedWorld
var config = new GameConfig();
using var chunkManager = ChunkManager.Create(config);
using var sharedMetadata = new SharedArchetypeMetadata(config);
using var chunkTagRegistry = new ChunkTagRegistry<ImmutableBitSet32>(config.ChunkAllocator, GameConfig.MaxMetaBlocks, GameConfig.ChunkSize);

// Create the world using the generated World alias
using var world = new World(config, chunkManager, sharedMetadata, chunkTagRegistry);

// Run all samples in sequence
var (emptyEntity, playerEntity, enemies) = EntityCreationSample.Run(world);
ComponentAccessSample.Run(world, playerEntity);
TagSystemSample.Run(world, playerEntity);
StructuralChangesSample.Run(world, emptyEntity);
EntityLifecycleSample.Run(world, enemies);
var movableQuery = ComponentQuerySample.Run(world);
TagQuerySample.Run(world, playerEntity);
GameLoopSample.Run(world, movableQuery);
EntityOverwriteSample.Run(world, playerEntity);
GeneratedTypesSample.Run();
WorldClearSample.Run(world, playerEntity);

Console.WriteLine("=== Sample Application Complete ===");
Console.WriteLine("All operations executed successfully!");

return 0;
