using Paradise.ECS.Sample;
using Paradise.ECS.Sample.Samples;

// The 'World' type alias is generated by the source generator when Paradise.ECS.Tag is referenced.
// It resolves to: TaggedWorld<SmallBitSet<ulong>, GameConfig, EntityTags, TagMask>
// The 'SharedWorld' alias is also generated for the shared resource container.

Console.WriteLine("=== Paradise.ECS Sample Application ===");
Console.WriteLine();

// Create the SharedWorld using the generated SharedWorldFactory - handles all dependencies automatically!
// SharedWorld owns ChunkManager, SharedArchetypeMetadata, and ChunkTagRegistry internally.
// Multiple World instances can be created from a single SharedWorld to share resources.
// SharedWorld is IDisposable and cleans up all resources when disposed.
using var sharedWorld = SharedWorldFactory.Create();
var world = sharedWorld.CreateWorld();

// Run all samples in sequence
var (emptyEntity, playerEntity, enemies) = EntityCreationSample.Run(world);
ComponentAccessSample.Run(world, playerEntity);
TagSystemSample.Run(world, playerEntity);
StructuralChangesSample.Run(world, emptyEntity);
EntityLifecycleSample.Run(world, enemies);
var movableQuery = ComponentQuerySample.Run(world);
TagQuerySample.Run(world, playerEntity);
GameLoopSample.Run(world, movableQuery);
EntityOverwriteSample.Run(world, playerEntity);
GeneratedTypesSample.Run();
QueryableSample.Run(world);
SystemSample.Run(world);
WorldClearSample.Run(world, playerEntity);

Console.WriteLine("=== Sample Application Complete ===");
Console.WriteLine("All operations executed successfully!");

return 0;
